version: '3'
services:
  recruitable_db:
    container_name: evally_recruitable_db
    image: postgres:10.6-alpine
    volumes:
      - postgres:/var/lib/postgresql/data

  recruitable_app:
    environment:
      - RAILS_ENV=development
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: evally_recruitable_app
    command: bin/rails s -p 3030 -b '0.0.0.0'
    user: ${CURRENT_USER}
    volumes:
      - .:/app
      - ./config/database.example.yml:/app/config/database.yml
      - ./docker/env.example.yml:/app/config/env.yml
    ports:
      - '3030:3030'
    depends_on:
      - recruitable_db

volumes:
  postgres:

networks:
  default:
    external:
      name: evally_network

# docker network create evally_network --subnet 172.24.24.0/24
# CURRENT_USER=$(id -u):$(id -g) add to .bashrc / .zshrc to run container as non-root user
